### PR TITLE
Profi200 sdmmc code

### PR DESCRIPTION
**Pull request by ahezard**
It works very well! Thanks to profi200.

### CODE REVIEW

**Comment by piratesephiroth** [comment]
I'm not sure if it was this commit or the one that removes donor roms but the unreleased Tetris DS from THQ works flawless now

**Comment by Robz8** [comment]
It's the one that removes donor ROMs, as Tetris DS is loaded fully into RAM (on 3DS).

**Comment by piratesephiroth** [comment]
the only problem with that is that now only SDK2 games work, because TWLoader demands a donor rom for the newer games and if we pick one nds-bootstrap will ignore it and the game will throw the save data error, lol

**Comment by Valeri0p** [comment]
Is this the so long prophesied "arm9 sd read?" 😳 because iirc the 3ds doesn't use the arm7 during boot, right?
It is faster?

**Comment by piratesephiroth** [comment]
>It is faster?
I didn't notice any difference on speed

**Comment by Robz8** [comment]
@Valeri0p Sadly, it's still arm7 doing the reads. :P

**Comment by Robz8** [comment]
@piratesephiroth It's only noticeable with small load times.

**Pull request merged**
