### PR TITLE
Make In-Game Menu translatable

### PR DESCRIPTION
**Pull request by Epicpkmn11**
Makes the in-game menu translatable. Has Japanese as an example currently, set the GUI language by setting `GUI_LANGUAGE` to the language's two letter code (or two letter dash country) in the ini.

```ini
; nds-bootstrap.ini
[NDS-BOOTSTRAP]
...
GUI_LANGUAGE = ja
```

TODO:
- [x] Fix overwriting in-game menu code (**NOTE**: Fixed, but not sure if it's fixed in a good way)
  - I'd like help with this please 😅, currently it's loading the strings over the code
  - `(struct IgmText *)INGAME_MENU_LOCATION` (retail/common/include/igm_text.h#15) just needs to be changed to somewhere safe
  - Currently the struct needs 790 bytes. Some strings could be optimized, but I want to leave plenty of room for translations
- [x] Add to Crowdin
  - [x] Fix ini parsing not working without spaces around `=`, Crowdin only exports without spaces
    - Also removed the fstreams and regex from libeasysave which saves like 300 KB(!) that's like a whole third the of nds-bootstrap
- [x] Add more scripts to font
  - [x] Latin
  - [x] Extended Latin
  - [x] Hiragana
  - [ ] Katakana (Unlikely, hiragana only is readable enough)
  - [x] Cyrillic
  - [x] Hebrew
  - [ ] Hangul (will be done as needed)
  - [x] Chinese (will be done as needed)
    - I don't really want to include Chinese characters to keep the size down. Japanese is usable with just hiragana and/or katakana but not sure what to do for Chinese... Doing it romanized or *maybe* including just the bare minimum characters might work?
  - [x] Probably remove / change the libnds special characters below ASCII. Can probably replace them with like Hebrew or Cyrillic or so if they fit or just some more useful special characters like battery icons
  - Current font is this: (Suggestions for changes are welcome. The symbols below ASCII are based on the libnds default, but the whole font is changed as Kana would be hard to do thick. I could maybe do think latin and thin Kana though)
  The font
- [x] Also changes Makefile to ensure commit sha will always be 7 digits, not sometimes 8

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
I've added extended Latin, Cyrillic, Hebrew, and Hangul to the font. As I said above the Hangul are kinda lame, only the "compatibility" ones, but it might be better than nothing? If this isn't worth having I'll remove it to save a bit of space.

Updated font
Suggestions are welcome, I only really know English and a Hiragana reasonably well. (Also, yes that is a fancy battery icon ;P)

I've also moved it to put the strings [right before `INGAME_MENU_LOCATION`](https://github.com/DS-Homebrew/nds-bootstrap/pull/1126/files#diff-a21b8f5e38b8a78deae1bf2e83cdcf910d36fad029ea492aa3c82979d3fdefb5R15), this fixes freezing on load and doesn't *seem* to break anything but I dunno.

**Comment by chyyran** [comment]
Just having individual jamo is not readable, I would probably leave it out if syllable blocks can't be constructed.

**Comment by Epicpkmn11** [comment]
Removed Hangul, added to [Crowdin](https://crowdin.com/project/nds-bootstrap), and added RTL handling so marking this ready for review.

The only concern I have at the moment is where I'm putting the in-game menu text struct, no idea if that's a safe location for it, but it's worked so far.

**Comment by Epicpkmn11** [comment]
Added Chinese:
ds_full

I'm not entirely happy with this, but you try making a 7x7 Chinese font ;P
The Chinese is 2 colors as the font is 4 bpp so might as well make some use of that because it would've been completely unreadable with only 1 color, as is I think it looks passable enough but suggestions are appreciated. I only know Japanese and am still fairly basic at that so I might've messed some stuff up.

If there are any differences these are mostly based on the Simplified forms as that's what I used for reference since it was the default font, with the exception of 返, 速, and 遊 which I did base on a Traditional font as I remembered that the ⻌ radical is different, the change is really minor though since the font is so tiny.

I suppose hangul can probably be done the same way if it can be kept under ideally 64 characters or so max, not sure how feasible that is but there are only 161 total characters in the English one so it might work.

I've been waiting to ping Translators on Discord until this is merged so kinda surprised anyone's done it yet lol.

**Comment by Epicpkmn11** [comment]
This is ready to merge fyi, the only potential major problem as far as I can tell is where the in-game menu text struct is at [igm_text.h#16](https://github.com/Epicpkmn11/nds-bootstrap/blob/translatable/retail/common/include/igm_text.h#L16), but if that's fine then this is good, if not then please let me know where is better.

**Pull request merged**
