### PR TITLE
Add AP patches and its loading mechanism

### LINKED ISSUE #1440: Move apfix file handling to nds-bootstrap
Issue template not relevant: enhancement ideas.

Branching off from issue #1437, ideally nds-bootstrap should handle the static apfix files itself, instead of having the frontend manually copy files into its designated location. 

My opinion hasn't changed on the fact that the frontend loading nds-bootstrap should do absolutely nothing other than run nds-bootstrap, and tell them which ROM and save it should run. All other detections should be done by the actual binary doing the game-running, so as to be less reliant on the frontend and let nds-bootstrap be a self-contained application.

Another interesting idea is that this would effectively nuke the need for packing all the apfixes into that `.pck` format, since we can get the same goal of less tiny files scattered on the SD card by just throwing the whole directory into NitroFS. We already know that AP patching is mission critical, so I don't see why it has to have a frontend providing it.

We can *probably* do the same thing for the widescreen cheats, but that is an optional setting so not relevant for now.

### PR DESCRIPTION
**Pull request by lifehackerhansol**
#### What's changed?

As of commit 393f838004da7 from TWiLightMenu. Fully implements and closes #1440.

The code is pretty much a direct copy from TWiLight, with the fcopy BSS a little smaller (we don't need to alloc 32KB of memory for copying, the files are on average less than 512 bytes. So only 512 bytes are alloc'd for now.)

The packaging of the apfixes is removed, and built directly into NitroFS instead. Not much is lost here, as the only reason we were using that packing was solely because small file sizes meant slower extraction for Universal Updater and the like.

Ideally, we'd place the config function in `loadFromSD`. But it keeps crashing there, but it doesn't crash in `load_conf`. So just keep it there for now.

TODO: 
- [x] Implement the AP patching
- [x] Implement AP patch overriding
  - [x] by gameTID:headerCRC
  - [x] by filename
- [ ] Remove the code from TWiLight

For people who want to test:
1. Nuke all AP fix packs and override files from the `TWiLightMenu/extras` folder
2. Build this branch (or DL from GitHub Actions I guess) and place build on SD card appropriately
3. Turn on debug. AP fix path will be shown in the debug screen.
4. Run game with known AP fix and see if it behaves (I am testing a clean Black 2 dump.)

#### Where have you tested it?

Nintendo DSi
needs more testing, such as overriding and/or flashcard with SCFG access etc.

***

#### Pull Request status
- [x] This PR has been tested using the latest version of devkitARM and libnds.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
A change to TWiLight is obviously required. For example, TWiLight supplies a "this game has Anti-Piracy" messages, which won't be available anymore since this change makes it unnecessary for TWiLight to ship AP patches.

One could probably mount the NitroFS and check it. It's messy, and probably increases latency, but the option is there, since AP patches are stored in NitroFS verbatim.

**Comment by Vaporeon** [comment]
It is really required to write these ips files to the sd card? I have not read over the whole thing so maybe there is a reason for this, but would it not be better to do it completely in memory?

**Comment by lifehackerhansol** [comment]
> It is really required to write these ips files to the sd card? I have not read over the whole thing so maybe there is a reason for this, but would it not be better to do it completely in memory?

It likely is possible to put it in memory, but I didn't want to touch the `bootloader` module, which is responsible for loading it to memory. That's its own thing entirely, and doesn't even make use of stdio. I could theoretically load it into the `IPS_LOCATION` address, but I'm not sure how `bootloader` is handling AP cheat codes. The `apPatchIsCheat` doesn't seem to be modified anywhere(?)

But for now, I say we get the ball rolling at least, until we figure out how much more optimizing is possible.

**Comment by lifehackerhansol** [comment]
Overriding AP patches via gamecode:headerCRC is working. Filename comparison is not working, as filename parsing is unimplemented. TWiLight didn't need this since it can just chdir when user enters a folder, we don't do that here.

**Comment by lifehackerhansol** [comment]
For whatever reason, it doesn't work with R4 Ultra in DSi-mode. Can't seem to find out why that is.

**Comment by lifehackerhansol** [comment]
logs of running this build on R4 Ultra via Slot-1 microSD access:
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/nds-bootstrap/files/9391744/NDSBTSRP.LOG)

The issue with SCFG access cards seem to be related to #1443, but even if that was fixed there likely will be issues anyway similar to whatever is going on with my R4 Ultra...

**Comment by lifehackerhansol** [comment]
Rebased and updated patches as of https://github.com/DS-Homebrew/TWiLightMenu/commit/5559afd447e2e6af9eb08fa695a062e6ee767b6d.

Bug still not fixed :pensive:

**Comment by lifehackerhansol** [comment]
Rebased.
Currently with SCFG access in Slot-1 and running games from flashcart SD, the AP patch outright didn't apply. Not sure why that is. The AP does load as shown in debug.

**Pull request closed without merging**
